# configuration for https://travis-ci.org/andreynovikov/maptrek
sudo: false
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - extra-android-m2repository
os:
  - linux
env:
  global:
    - GRADLE_OPTS="-Xmx2048m -Dorg.gradle.parallel=true"
install:
  - echo y | sdkmanager "ndk-bundle"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
  - chmod +x gradlew
script:
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - ./gradlew clean build -x lint -x lintVitalRelease --warning-mode all
